### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by 0silverback0** [0silverback0/TrainerAppFrontend#1]
I would like the read me updated with hacktoberfest images, also please me the content more clear

**Comment by Shreya111111** [comment]
@0silverback0  can i work on this issue

**Comment by 0silverback0** [comment]
Go for it!

**Comment by somdipto** [comment]
can i work on this isue  ,, if its open...

**Comment by 0silverback0** [comment]
I assigned you

**Comment by DanielZhang111** [comment]
Can I get assigned??

**Comment by 0silverback0** [comment]
I have assigned to others but no commits yet so have a go at it, I'll assign you as well

**Comment by czarjulius** [comment]
@0silverback0 After observing that the problem persisted despite multiple assignments, I made the decision to submit a pull request to address it. Your review is greatly appreciated.  🙏
