### ISSUE TITLE
Deploy this project to netlify

### ISSUE THREAD

**Issue by mdtausifiqbal** [0silverback0/TrainerAppFrontend#4]
@0silverback0 please deploy this project to netlify, so that whenever anyone create a PR, we can see live preview of app.

**Comment by 0silverback0** [comment]
I will be deploying the project shortly.

**Comment by 0silverback0** [comment]
i have started a basic home page for this repo and have it deployed to netlify. take it away from here if you like

**Comment by 0silverback0** [comment]
this site is now deployed here https://chipper-bavarois-bf1c55.netlify.app/ im going to close this issue, and you are free to make your changes. I like your work so im excited to see what you do
