### ISSUE TITLE
adding features like routing and toggling of sidebar

### ISSUE THREAD

**Issue by weberankit** [0silverback0/TrainerAppFrontend#7]
I like to add features like routing the nav link and toggling the sidebar 

could you plz assign this issue to me under Hactoberfest? 

![image](https://github.com/0silverback0/TrainerAppFrontend/assets/94105514/47387fce-f757-40fd-a28b-4b3d37c3a4f1)

**Comment by 0silverback0** [comment]
Go for it!

**Comment by weberankit** [comment]
@0silverback0  plz merge issue #8

**Comment by weberankit** [comment]
completed
